# Generated by Django 4.2.14 on 2024-12-04 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(help_text='Title in Russian', max_length=155, verbose_name='Title (Russian)')),
                ('title_uz', models.CharField(help_text='Title in Uzbek', max_length=155, verbose_name='Title (Uzbek)')),
                ('title', models.CharField(help_text='Title', max_length=155, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(blank=True, editable=False, help_text='Telegram ID', max_length=155, null=True, verbose_name='Telegram ID')),
                ('name', models.CharField(blank=True, editable=False, help_text='Name', max_length=155, null=True, verbose_name='Name')),
                ('telegram_username', models.CharField(blank=True, editable=False, help_text='Telegram Username', max_length=155, null=True, verbose_name='Telegram Username')),
                ('phone_number', models.CharField(blank=True, editable=False, help_text='Phone Number', max_length=155, null=True, verbose_name='Phone Number')),
                ('city', models.CharField(blank=True, default='Ташкент', help_text='City', max_length=155, null=True, verbose_name='City')),
                ('preferred_language', models.CharField(blank=True, choices=[('ru', 'Russian'), ('uz', 'Uzbek'), ('en', 'English'), ('fr', 'French')], help_text='Preferred language for bot interaction', max_length=50, null=True, verbose_name='Preferred Language')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(help_text='Title in Russian', max_length=155, verbose_name='Title (Russian)')),
                ('title_uz', models.CharField(help_text='Title in Uzbek', max_length=155, verbose_name='Title (Uzbek)')),
                ('title', models.CharField(help_text='Title', max_length=155, verbose_name='Title')),
                ('price', models.FloatField(help_text='Price', verbose_name='Price')),
                ('image', models.ImageField(help_text='Image', upload_to='', verbose_name='Image')),
                ('is_small', models.BooleanField(default=False, verbose_name='Маленький размер')),
                ('is_big', models.BooleanField(default=False, verbose_name='Большой размер')),
                ('small_volume', models.PositiveIntegerField(default=250, verbose_name='Объем маленького размера (мл)')),
                ('big_volume', models.PositiveIntegerField(default=500, verbose_name='Объем большого размера (мл)')),
                ('is_hot', models.BooleanField(default=False, verbose_name='Горячий')),
                ('is_cold', models.BooleanField(default=False, verbose_name='Холодный')),
                ('category', models.ForeignKey(help_text='Category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField()),
                ('courier_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя курьера')),
                ('car_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер машины')),
                ('car_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Модель машины')),
                ('delivery_cost', models.IntegerField(default=0)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('delivering', 'Delivering'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('closed', 'Closed')], default='pending', max_length=50)),
                ('cart_data_json', models.JSONField(blank=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.client')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Quantity', verbose_name='Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time of cart creation', verbose_name='Created At')),
                ('is_small', models.BooleanField(default=False, verbose_name='Маленький размер')),
                ('is_big', models.BooleanField(default=False, verbose_name='Большой размер')),
                ('is_hot', models.BooleanField(default=False, verbose_name='Горячий')),
                ('is_cold', models.BooleanField(default=False, verbose_name='Холодный')),
                ('client', models.ForeignKey(help_text='Client', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.client', verbose_name='Client')),
                ('product', models.ForeignKey(help_text='Product', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'unique_together': {('client', 'product', 'is_small', 'is_big', 'is_hot', 'is_cold')},
            },
        ),
    ]
