# Generated by Django 4.2.14 on 2024-12-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='big_price',
            field=models.PositiveIntegerField(blank=True, help_text='Price for big size in local currency', null=True, verbose_name='Big Size Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='small_price',
            field=models.PositiveIntegerField(blank=True, help_text='Price for small size in local currency', null=True, verbose_name='Small Size Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='big_volume',
            field=models.PositiveIntegerField(default=500, help_text='Volume of big size in milliliters', verbose_name='Big Volume (ml)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Image', null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_big',
            field=models.BooleanField(default=False, help_text='Product has big size option', verbose_name='Has Big Size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_cold',
            field=models.BooleanField(default=False, help_text='Product has cold option', verbose_name='Cold Option'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_hot',
            field=models.BooleanField(default=False, help_text='Product has hot option', verbose_name='Hot Option'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_small',
            field=models.BooleanField(default=False, help_text='Product has small size option', verbose_name='Has Small Size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='small_volume',
            field=models.PositiveIntegerField(default=250, help_text='Volume of small size in milliliters', verbose_name='Small Volume (ml)'),
        ),
    ]
